### ISSUE TITLE
CarriageReturn or LineFeed

### ISSUE THREAD

**Issue by m5p3nc3r** [rustne-kretser/noline#18]
Hi

I am having issues when using base64 to stream data through noline.  If I use a command under a unix like system (macos)

```
base64 -b64 -i <file>
```

the line endings are LF not CR, so I don't get any lines read from the input stream with noline.

I must admit I'm no expert in the dark arts of line endings, and the differences between OS's views of the LF/CRLF, but if I change the core::Line::advance to:

```diff
-CarriageReturn => {
+CarriageReturn | LineFeed => {
    if self.buffer.len() > 0 {
        let _ = self.nav.history.add_entry(self.buffer.as_str());
    }

    self.generate_output(Done)
}
```

I am able to process normal input from stdin, but also piped input from a unix command.

Is this a sensible change, or am I mis-understanding the problem>

**Comment by eivindbergem** [comment]
Pressing Enter inputs a CR in the terminal, so it's not really a newline in this context. I never tested with pasting lines in, so I didn't encounter this problem. Accepting LF in this case seems reasonable to me. Create a PR, and I'll merge it in.

**Comment by m5p3nc3r** [comment]
I have create #19 to implement this.
